/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationCreateBodyOriginType = typeof CustomerLocationCreateBodyOriginType[keyof typeof CustomerLocationCreateBodyOriginType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationCreateBodyOriginType = {
  home: 'home',
  commercial: 'commercial',
} as const;
