/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerAvailabilityShippingOrigin = {
  customerId?: string;
  distanceForFree?: number;
  distanceHourlyRate?: number;
  fixedRatePerKm?: number;
  fullAddress?: string;
  name?: string;
  startFee?: number;
};
