/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutLog} from './customerPayoutLog';

export interface CustomerPayoutLogPayload {
  currentPage: number;
  hasNextPage: boolean;
  results: CustomerPayoutLog[];
  totalCount: number;
  totalPages: number;
}
