/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBookingPeriod} from './customerProductBookingPeriod';
import type {CustomerProductUpdateBodyCompareAtPrice} from './customerProductUpdateBodyCompareAtPrice';
import type {CustomerProductLocations} from './customerProductLocations';
import type {CustomerProductNoticePeriod} from './customerProductNoticePeriod';
import type {CustomerProductUpdateBodyPrice} from './customerProductUpdateBodyPrice';
import type {CustomerProductUpdateBodySelectedOptions} from './customerProductUpdateBodySelectedOptions';

export interface CustomerProductUpdateBody {
  bookingPeriod?: CustomerProductBookingPeriod;
  breakTime?: number;
  compareAtPrice?: CustomerProductUpdateBodyCompareAtPrice;
  description?: string;
  duration?: number;
  locations?: CustomerProductLocations;
  noticePeriod?: CustomerProductNoticePeriod;
  price?: CustomerProductUpdateBodyPrice;
  scheduleId: string;
  selectedOptions?: CustomerProductUpdateBodySelectedOptions;
  variantId?: number;
}
