/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccountCreateBodyPayoutDetails} from './customerPayoutAccountCreateBodyPayoutDetails';
import type {CustomerPayoutAccountType} from './customerPayoutAccountType';

export type CustomerPayoutAccountCreateBody = {
  payoutDetails: CustomerPayoutAccountCreateBodyPayoutDetails;
  payoutType: CustomerPayoutAccountType;
};
