/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutMobilePay} from './customerPayoutMobilePay';
import type {CustomerPayoutBankAccount} from './customerPayoutBankAccount';

export type CustomerPayoutAccountPayoutDetails =
  | CustomerPayoutMobilePay
  | CustomerPayoutBankAccount;
