/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccountDestroy200Payload} from './customerPayoutAccountDestroy200Payload';

export type CustomerPayoutAccountDestroy200 = {
  payload: CustomerPayoutAccountDestroy200Payload;
  success: boolean;
};
