/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccountGet200Payload} from './customerPayoutAccountGet200Payload';

export type CustomerPayoutAccountGet200 = {
  payload: CustomerPayoutAccountGet200Payload;
  success: boolean;
};
