/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationBaseOriginType =
  (typeof CustomerLocationBaseOriginType)[keyof typeof CustomerLocationBaseOriginType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationBaseOriginType = {
  home: 'home',
  commercial: 'commercial',
} as const;
