/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderLineItemResponse} from './customerOrderLineItemResponse';

export type CustomerOrderResponseAllOf = {
  line_items: CustomerOrderLineItemResponse[];
};
