/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerCreateBodySocial} from './customerCreateBodySocial';

export interface CustomerCreateBody {
  aboutMe: string;
  customerId: number;
  email: string;
  fullname: string;
  gender: string;
  phone: string;
  professions: string[];
  shortDescription: string;
  social: CustomerCreateBodySocial;
  speaks: string[];
  specialties: string[];
  /** @pattern ^[a-zA-Z0-9-_]+$ */
  username: string;
  yearsExperience: string;
}
