/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerProductLocationsItemOriginType =
  (typeof CustomerProductLocationsItemOriginType)[keyof typeof CustomerProductLocationsItemOriginType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerProductLocationsItemOriginType = {
  home: 'home',
  commercial: 'commercial',
} as const;
