/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerUpdateBodySocial = {
  instagram?: string;
  twitter?: string;
  youtube?: string;
};
