/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerProductNoticeUnit =
  (typeof CustomerProductNoticeUnit)[keyof typeof CustomerProductNoticeUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerProductNoticeUnit = {
  hours: 'hours',
  days: 'days',
  weeks: 'weeks',
} as const;
