/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerProductBookingUnit } from './customerProductBookingUnit';

export interface CustomerProductBookingPeriod {
  unit: CustomerProductBookingUnit;
  value: number;
}
