/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerOrderAddress {
  address1?: string;
  address2?: string | null;
  city?: string;
  company?: string | null;
  country?: string;
  country_code: string;
  country_name?: string;
  customer_id?: number;
  default: boolean;
  first_name: string;
  last_name: string;
  latitude?: number | null;
  longitude?: number | null;
  name: string;
  phone?: string;
  province?: string | null;
  province_code?: string;
  zip?: string;
}
