/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductLocationsItemLocationType} from './customerProductLocationsItemLocationType';
import type {CustomerProductLocationsItemOriginType} from './customerProductLocationsItemOriginType';

export type CustomerProductLocationsItem = {
  location: string;
  locationType: CustomerProductLocationsItemLocationType;
  originType: CustomerProductLocationsItemOriginType;
};
