/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductAddBodyCompareAtPrice} from './customerProductAddBodyCompareAtPrice';
import type {CustomerProductLocations} from './customerProductLocations';
import type {CustomerProductAddBodyPrice} from './customerProductAddBodyPrice';

export interface CustomerProductAddBody {
  compareAtPrice: CustomerProductAddBodyCompareAtPrice;
  hideFromCombine: string;
  hideFromProfile: string;
  locations: CustomerProductLocations;
  parentId: string;
  price: CustomerProductAddBodyPrice;
  scheduleId: string;
  title: string;
}
