/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionVariantsNodesItemDuration} from './customerProductOptionVariantsNodesItemDuration';

export type CustomerProductOptionVariantsNodesItem = {
  duration: CustomerProductOptionVariantsNodesItemDuration;
  id: string;
  price: string;
  title: string;
};
