/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccount} from './customerPayoutAccount';

export type CustomerPayoutAccountGet200 = {
  payload: CustomerPayoutAccount;
  success: boolean;
};
