/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationCreateBodyLocationType =
  (typeof CustomerLocationCreateBodyLocationType)[keyof typeof CustomerLocationCreateBodyLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationCreateBodyLocationType = {
  origin: 'origin',
  destination: 'destination',
} as const;
