/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccountDestroy} from './customerPayoutAccountDestroy';

export interface CustomerPayoutAccountDestroyResponse {
  payload: CustomerPayoutAccountDestroy;
  success: boolean;
}
