/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBookingPeriod} from './customerProductBookingPeriod';
import type {CustomerProductBaseBreakTime} from './customerProductBaseBreakTime';
import type {CustomerProductBaseDuration} from './customerProductBaseDuration';
import type {CustomerProductNoticePeriod} from './customerProductNoticePeriod';

export interface CustomerProductBase {
  bookingPeriod: CustomerProductBookingPeriod;
  breakTime: CustomerProductBaseBreakTime;
  description?: string;
  duration: CustomerProductBaseDuration;
  noticePeriod: CustomerProductNoticePeriod;
  productId: number;
  variantId: number;
}
