/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationUpdateBodyOriginType} from './customerLocationUpdateBodyOriginType';

export interface CustomerLocationUpdateBody {
  distanceForFree: number;
  distanceHourlyRate: number;
  fixedRatePerKm: number;
  fullAddress: string;
  maxDriveDistance: number;
  minDriveDistance: number;
  name: string;
  originType: CustomerLocationUpdateBodyOriginType;
  startFee: number;
}
