/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationIsDefault} from './customerLocationIsDefault';

export interface CustomerLocationListResponse {
  payload: CustomerLocationIsDefault[];
  success: boolean;
}
