/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductAddBodyCompareAtPrice} from './customerProductAddBodyCompareAtPrice';
import type {CustomerProductLocations} from './customerProductLocations';
import type {CustomerProductAddBodyPrice} from './customerProductAddBodyPrice';

export interface CustomerProductAddBody {
  compareAtPrice: CustomerProductAddBodyCompareAtPrice;
  description: string;
  descriptionHtml: string;
  hideFromCombine: string;
  hideFromProfile: string;
  locations: CustomerProductLocations;
  price: CustomerProductAddBodyPrice;
  productType: string;
  scheduleId: string;
  title: string;
}
