/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerLocationUpdateBody {
  distanceForFree: number;
  distanceHourlyRate: number;
  fixedRatePerKm: number;
  fullAddress: string;
  maxDriveDistance: number;
  minDriveDistance: number;
  name: string;
  startFee: number;
}
