/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerProductBookingUnit =
  (typeof CustomerProductBookingUnit)[keyof typeof CustomerProductBookingUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerProductBookingUnit = {
  weeks: 'weeks',
  months: 'months',
} as const;
