/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerBaseOrderMoney } from './customerBaseOrderMoney';
import type { CustomerBaseOrderLineItemProperties } from './customerBaseOrderLineItemProperties';

export interface CustomerBaseOrderLineItem {
  admin_graphql_api_id: string;
  fulfillable_quantity: number;
  fulfillment_service: string;
  fulfillment_status?: string;
  gift_card: boolean;
  grams: number;
  id: number;
  name: string;
  price: string;
  price_set: CustomerBaseOrderMoney;
  product_exists: boolean;
  product_id: number;
  properties: CustomerBaseOrderLineItemProperties;
  quantity: number;
  requires_shipping: boolean;
  sku?: string;
  taxable: boolean;
  title: string;
  total_discount: string;
  total_discount_set: CustomerBaseOrderMoney;
  variant_id: number;
  variant_inventory_management?: string;
  variant_title?: string;
  vendor?: string;
}
