/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBookingPeriod} from './customerProductBookingPeriod';
import type {CustomerProductLocations} from './customerProductLocations';
import type {CustomerProductNoticePeriod} from './customerProductNoticePeriod';

export interface CustomerProductUpsertBody {
  bookingPeriod: CustomerProductBookingPeriod;
  breakTime: number;
  duration: number;
  locations: CustomerProductLocations;
  noticePeriod: CustomerProductNoticePeriod;
  scheduleId: string;
  variantId: number;
}
