/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerPayoutStatus =
  (typeof CustomerPayoutStatus)[keyof typeof CustomerPayoutStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerPayoutStatus = {
  Pending: 'Pending',
  Processed: 'Processed',
  Failed: 'Failed',
} as const;
