/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderWithLookupAllOfUserImages} from './customerOrderWithLookupAllOfUserImages';

export type CustomerOrderWithLookupAllOfUser = {
  customerId: number;
  fullname: string;
  images: CustomerOrderWithLookupAllOfUserImages;
  shortDescription: string;
  username: string;
};
