/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerBookingGetParams = {
  /**
   * date for the lineItem (2014-12-12)
   */
  date: string;
};
