/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {Items} from './items';

export interface CustomerProductOptionsAddResponse {
  payload: Items;
  success: boolean;
}
