/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBookingsListMode} from './customerBookingsListMode';

export type CustomerBookingsListParams = {
  /**
   * either "upcoming", "completed"
   */
  mode: CustomerBookingsListMode;
};
