/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutLogPayload} from './customerPayoutLogPayload';

export interface CustomerPayoutLogResponse {
  payload: CustomerPayoutLogPayload;
  success: boolean;
}
