/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionVariantsItem} from './customerProductOptionVariantsItem';

export interface CustomerProductOption {
  productId: number;
  title: string;
  variants: CustomerProductOptionVariantsItem[];
}
