/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionsAddResponsePayloadVariantsItemDuration} from './customerProductOptionsAddResponsePayloadVariantsItemDuration';

export type CustomerProductOptionsAddResponsePayloadVariantsItem = {
  duration: CustomerProductOptionsAddResponsePayloadVariantsItemDuration;
  price: string;
  title: string;
  variantId: number;
};
