/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationCreateBodyDistanceForFree} from './customerLocationCreateBodyDistanceForFree';
import type {CustomerLocationCreateBodyDistanceHourlyRate} from './customerLocationCreateBodyDistanceHourlyRate';
import type {CustomerLocationCreateBodyFixedRatePerKm} from './customerLocationCreateBodyFixedRatePerKm';
import type {CustomerLocationCreateBodyLocationType} from './customerLocationCreateBodyLocationType';
import type {CustomerLocationCreateBodyMaxDriveDistance} from './customerLocationCreateBodyMaxDriveDistance';
import type {CustomerLocationCreateBodyMinDriveDistance} from './customerLocationCreateBodyMinDriveDistance';
import type {CustomerLocationCreateBodyOriginType} from './customerLocationCreateBodyOriginType';
import type {CustomerLocationCreateBodyStartFee} from './customerLocationCreateBodyStartFee';

export interface CustomerLocationCreateBody {
  distanceForFree: CustomerLocationCreateBodyDistanceForFree;
  distanceHourlyRate: CustomerLocationCreateBodyDistanceHourlyRate;
  fixedRatePerKm: CustomerLocationCreateBodyFixedRatePerKm;
  fullAddress: string;
  locationType: CustomerLocationCreateBodyLocationType;
  maxDriveDistance: CustomerLocationCreateBodyMaxDriveDistance;
  minDriveDistance: CustomerLocationCreateBodyMinDriveDistance;
  name: string;
  originType: CustomerLocationCreateBodyOriginType;
  startFee?: CustomerLocationCreateBodyStartFee;
}
