/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationAllOfGeoLocationType =
  (typeof CustomerLocationAllOfGeoLocationType)[keyof typeof CustomerLocationAllOfGeoLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationAllOfGeoLocationType = {
  Point: 'Point',
} as const;
