/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerStatus } from './customerStatus';

export interface CustomerStatusResponse {
  payload: CustomerStatus;
  success: boolean;
}
