/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderSimpleLineItem} from './customerOrderSimpleLineItem';
import type {CustomerOrderRefundRefundLineItemsItemSubtotal} from './customerOrderRefundRefundLineItemsItemSubtotal';
import type {CustomerOrderMoney} from './customerOrderMoney';
import type {CustomerOrderRefundRefundLineItemsItemTotalTax} from './customerOrderRefundRefundLineItemsItemTotalTax';

export type CustomerOrderRefundRefundLineItemsItem = {
  id: number;
  line_item: CustomerOrderSimpleLineItem;
  line_item_id: number;
  location_id: number;
  quantity: number;
  restock_type: string;
  subtotal: CustomerOrderRefundRefundLineItemsItemSubtotal;
  subtotal_set: CustomerOrderMoney;
  total_tax?: CustomerOrderRefundRefundLineItemsItemTotalTax;
  total_tax_set?: CustomerOrderMoney;
};
