/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerProductAddBodyCompareAtPrice } from './customerProductAddBodyCompareAtPrice';
import type { CustomerProductLocations } from './customerProductLocations';
import type { CustomerProductAddBodyPrice } from './customerProductAddBodyPrice';
import type { CustomerProductAddBodySelectedOptions } from './customerProductAddBodySelectedOptions';

export interface CustomerProductAddBody {
  compareAtPrice?: CustomerProductAddBodyCompareAtPrice;
  locations: CustomerProductLocations;
  price: CustomerProductAddBodyPrice;
  productHandle: string;
  scheduleId: string;
  selectedOptions: CustomerProductAddBodySelectedOptions;
  variantId: number;
}
