/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerBlocked } from './customerBlocked';

export interface CustomerBlockedRangeResponse {
  payload: CustomerBlocked[];
  success: boolean;
}
