/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerProductBase } from './customerProductBase';
import type { CustomerProductAllOf } from './customerProductAllOf';

export type CustomerProduct = CustomerProductBase & CustomerProductAllOf;
