/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerUploadResourceURLResponsePayloadParametersItem} from './customerUploadResourceURLResponsePayloadParametersItem';

export type CustomerUploadResourceURLResponsePayload = {
  parameters: CustomerUploadResourceURLResponsePayloadParametersItem[];
  resourceUrl?: string;
  url: string;
};
