/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductDestroyResponsePayload} from './customerProductDestroyResponsePayload';

export interface CustomerProductDestroyResponse {
  payload: CustomerProductDestroyResponsePayload;
  success: boolean;
}
