/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBookingAllOfUserImages} from './customerBookingAllOfUserImages';

export type CustomerBookingAllOfUser = {
  customerId: number;
  fullname: string;
  images: CustomerBookingAllOfUserImages;
  shortDescription: string;
  username: string;
};
