/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBookingLineItemsItemPriceSet} from './customerBookingLineItemsItemPriceSet';
import type {CustomerBookingLineItemsItemStatus} from './customerBookingLineItemsItemStatus';
import type {CustomerBookingLineItemsItemTotalDiscountSet} from './customerBookingLineItemsItemTotalDiscountSet';

export type CustomerBookingLineItemsItem = {
  customerId: number;
  from: Date;
  lineItemId: number;
  priceSet: CustomerBookingLineItemsItemPriceSet;
  productId: number;
  status: CustomerBookingLineItemsItemStatus;
  title: string;
  to: Date;
  totalDiscountSet: CustomerBookingLineItemsItemTotalDiscountSet;
  variantId: number;
};
