/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionsAddResponsePayloadVariantsItem} from './customerProductOptionsAddResponsePayloadVariantsItem';

export type CustomerProductOptionsAddResponsePayload = {
  productId: number;
  title: string;
  variants: CustomerProductOptionsAddResponsePayloadVariantsItem[];
};
