/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerPayoutLogType = typeof CustomerPayoutLogType[keyof typeof CustomerPayoutLogType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerPayoutLogType = {
  Shipping: 'Shipping',
  LineItem: 'LineItem',
} as const;
