/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionVariants} from './customerProductOptionVariants';

export interface CustomerProductOption {
  id: string;
  title: string;
  variants: CustomerProductOptionVariants;
}
