/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationIsDefault} from './customerLocationIsDefault';
import type {CustomerOrderSingleLineItem} from './customerOrderSingleLineItem';
import type {CustomerOrderGetLineItemProduct} from './customerOrderGetLineItemProduct';
import type {Shipping} from './shipping';

export interface CustomerOrderGetLineItem {
  location: CustomerLocationIsDefault;
  order: CustomerOrderSingleLineItem;
  product: CustomerOrderGetLineItemProduct;
  shipping?: Shipping;
}
