/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionsList} from './customerProductOptionsList';

export interface CustomerProductOptionsListResponse {
  payload: CustomerProductOptionsList;
  success: boolean;
}
