/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionsListItemVariantsItemDuration} from './customerProductOptionsListItemVariantsItemDuration';

export type CustomerProductOptionsListItemVariantsItem = {
  duration: CustomerProductOptionsListItemVariantsItemDuration;
  price: string;
  title: string;
  variantId: number;
};
