/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationBase} from './customerLocationBase';
import type {CustomerLocationAllOf} from './customerLocationAllOf';

export type CustomerLocation = CustomerLocationBase & CustomerLocationAllOf;
