/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerAvailability} from './customerAvailability';

export interface CustomerAvailabilityGetResponse {
  payload: CustomerAvailability[];
  success: boolean;
}
