/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderCustomer} from './customerOrderCustomer';
import type {Shipping} from './shipping';

export interface CustomerOrderShipping {
  customer: CustomerOrderCustomer;
  end: string;
  id: number;
  order_number: number;
  shipping: Shipping;
  start: string;
  title: string;
}
