/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderLineItem} from './customerOrderLineItem';
import type {CustomerOrderLineItemLookupAllOf} from './customerOrderLineItemLookupAllOf';

export type CustomerOrderLineItemLookup = CustomerOrderLineItem &
  CustomerOrderLineItemLookupAllOf;
