/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerStatus {
  locations: boolean;
  profile: boolean;
  profileImage: boolean;
  schedules: boolean;
  services: boolean;
}
