/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderMoneyPresentmentMoney} from './customerOrderMoneyPresentmentMoney';
import type {CustomerOrderMoneyShopMoney} from './customerOrderMoneyShopMoney';

export interface CustomerOrderMoney {
  presentment_money: CustomerOrderMoneyPresentmentMoney;
  shop_money: CustomerOrderMoneyShopMoney;
}
