/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccountCreateBodyPayoutDetails} from './customerPayoutAccountCreateBodyPayoutDetails';
import type {CustomerPayoutAccountType} from './customerPayoutAccountType';

export interface CustomerPayoutAccountCreateBody {
  payoutDetails: CustomerPayoutAccountCreateBodyPayoutDetails;
  payoutType: CustomerPayoutAccountType;
}
