/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerUpdateBodyImages} from './customerUpdateBodyImages';
import type {CustomerUpdateBodyProfessions} from './customerUpdateBodyProfessions';
import type {CustomerUpdateBodySocial} from './customerUpdateBodySocial';
import type {CustomerUpdateBodySpeaks} from './customerUpdateBodySpeaks';
import type {CustomerUpdateBodySpecialties} from './customerUpdateBodySpecialties';

export interface CustomerUpdateBody {
  aboutMe?: string;
  active?: boolean;
  customerId?: number;
  email?: string;
  fullname?: string;
  gender?: string;
  images?: CustomerUpdateBodyImages;
  phone?: string;
  professions?: CustomerUpdateBodyProfessions;
  shortDescription?: string;
  social?: CustomerUpdateBodySocial;
  speaks?: CustomerUpdateBodySpeaks;
  specialties?: CustomerUpdateBodySpecialties;
  username?: string;
  yearsExperience?: string;
}
