/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationBaseLocationType} from './customerLocationBaseLocationType';

export interface CustomerLocationBase {
  city: string;
  country: string;
  customerId: string;
  fullAddress: string;
  locationType: CustomerLocationBaseLocationType;
  metafieldId: string;
  name: string;
}
