/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerScheduleSlotDay =
  (typeof CustomerScheduleSlotDay)[keyof typeof CustomerScheduleSlotDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerScheduleSlotDay = {
  monday: 'monday',
  tuesday: 'tuesday',
  wednesday: 'wednesday',
  thursday: 'thursday',
  friday: 'friday',
  saturday: 'saturday',
  sunday: 'sunday',
} as const;
