/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderAddress} from './customerOrderAddress';
import type {CustomerOrderCustomerSmsMarketingConsent} from './customerOrderCustomerSmsMarketingConsent';

export interface CustomerOrderCustomer {
  accepts_marketing: boolean;
  accepts_marketing_updated_at?: string;
  admin_graphql_api_id: string;
  created_at: Date;
  currency: string;
  default_address?: CustomerOrderAddress;
  email?: string | null;
  email_marketing_consent?: boolean | null;
  first_name: string;
  id: number;
  last_name: string;
  marketing_opt_in_level?: string | null;
  multipass_identifier?: string | null;
  note?: string | null;
  phone?: string | null;
  sms_marketing_consent?: CustomerOrderCustomerSmsMarketingConsent;
  state: string;
  tags: string;
  tax_exempt: boolean;
  tax_exemptions?: string[];
  updated_at: Date;
  verified_email: boolean;
}
