/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationBaseLocationType = typeof CustomerLocationBaseLocationType[keyof typeof CustomerLocationBaseLocationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationBaseLocationType = {
  origin: 'origin',
  destination: 'destination',
} as const;
