/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrder} from './customerOrder';
import type {CustomerOrderWithLookupAllOf} from './customerOrderWithLookupAllOf';

export type CustomerOrderWithLookup = CustomerOrder &
  CustomerOrderWithLookupAllOf;
