/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerBaseOrderClient {
  accept_language?: string;
  browser_height?: number;
  browser_ip?: string;
  browser_width?: number;
  session_hash?: string;
  user_agent?: string;
}
