/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerUpdateBodySocial} from './customerUpdateBodySocial';

export interface CustomerUpdateBody {
  aboutMe?: string;
  email?: string;
  fullname?: string;
  gender?: string;
  phone?: string;
  professions?: string[];
  shortDescription?: string;
  social?: CustomerUpdateBodySocial;
  speaks?: string[];
  specialties?: string[];
  yearsExperience?: string;
}
