/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerCreateBody {
  aboutMe: string;
  aboutMeHtml: string;
  customerId: number;
  fullname: string;
  gender: string;
  /** @minItems 1 */
  professions: string[];
  /** @minLength 3 */
  shortDescription: string;
  /** @minItems 1 */
  speaks: string[];
  /** @pattern ^[a-zA-Z0-9-_]+$ */
  username: string;
}
