/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutMobilePay} from './customerPayoutMobilePay';
import type {CustomerPayoutBankAccount} from './customerPayoutBankAccount';

export type CustomerPayoutAccountCreateBodyPayoutDetails =
  | CustomerPayoutMobilePay
  | CustomerPayoutBankAccount;
