/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationOriginType =
  (typeof CustomerLocationOriginType)[keyof typeof CustomerLocationOriginType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationOriginType = {
  home: 'home',
  commercial: 'commercial',
} as const;
