/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductNoticeUnit} from './customerProductNoticeUnit';
import type {CustomerProductNoticePeriodValue} from './customerProductNoticePeriodValue';

export interface CustomerProductNoticePeriod {
  unit: CustomerProductNoticeUnit;
  value: CustomerProductNoticePeriodValue;
}
