/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderRange} from './customerOrderRange';

export interface CustomerOrderRangeResponse {
  payload: CustomerOrderRange[];
  success: boolean;
}
