/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationBase} from './customerLocationBase';
import type {CustomerOrderWithLookupAllOfUser} from './customerOrderWithLookupAllOfUser';

export type CustomerOrderWithLookupAllOf = {
  location: CustomerLocationBase;
  user: CustomerOrderWithLookupAllOfUser;
};
