/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderMoney} from './customerOrderMoney';

export interface CustomerOrderShippingLines {
  carrier_identifier?: string | null;
  code?: string | null;
  discounted_price: string;
  discounted_price_set: CustomerOrderMoney;
  id: number;
  phone?: string | null;
  price: string;
  price_set: CustomerOrderMoney;
  requested_fulfillment_service_id?: string | null;
  source: string;
  title: string;
}
