/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerPayoutPaginateParams = {
/**
 * The page number
 */
page: string;
/**
 * The sort order either asc eller desc = default desc
 */
sortOrder?: string;
/**
 * The limit = default to 10
 */
limit?: string;
};
