/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderLineItemLookupAllOfUserImages} from './customerOrderLineItemLookupAllOfUserImages';

export type CustomerOrderLineItemLookupAllOfUser = {
  customerId: number;
  fullname: string;
  images: CustomerOrderLineItemLookupAllOfUserImages;
  shortDescription: string;
  username: string;
};
