/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomeBaserOrderLineItem} from './customeBaserOrderLineItem';
import type {Shipping} from './shipping';

export type CustomerPayoutLogPayloadResultsItem =
  | CustomeBaserOrderLineItem
  | Shipping;
