/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocationBase} from './customerLocationBase';
import type {CustomerOrderLineItemLookupAllOfShipping} from './customerOrderLineItemLookupAllOfShipping';
import type {CustomerOrderLineItemLookupAllOfUser} from './customerOrderLineItemLookupAllOfUser';

export type CustomerOrderLineItemLookupAllOf = {
  location: CustomerLocationBase;
  shipping?: CustomerOrderLineItemLookupAllOfShipping;
  user: CustomerOrderLineItemLookupAllOfUser;
};
