/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerOrderClient {
  accept_language?: string | null;
  browser_height?: number | null;
  browser_ip?: string;
  browser_width?: number | null;
  session_hash?: string | null;
  user_agent?: string | null;
}
