/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerCreateBody {
  customerId: number;
  fullname: string;
  gender: string;
  /** @minItems 1 */
  speaks: string[];
  /**
   * @minItems 3
   * @pattern ^[a-zA-Z0-9\-_]*$
   */
  username: string;
}
