/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBookingUnit} from './customerProductBookingUnit';
import type {CustomerProductBookingPeriodValue} from './customerProductBookingPeriodValue';

export interface CustomerProductBookingPeriod {
  unit: CustomerProductBookingUnit;
  value: CustomerProductBookingPeriodValue;
}
