/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerLocationGeoLocationType =
  (typeof CustomerLocationGeoLocationType)[keyof typeof CustomerLocationGeoLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerLocationGeoLocationType = {
  Point: 'Point',
} as const;
