/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerBaseOrderAddress {
  address1?: string;
  address2?: string;
  city?: string;
  company?: string;
  country?: string;
  country_code: string;
  country_name?: string;
  customer_id?: number;
  default: boolean;
  first_name: string;
  last_name: string;
  latitude?: number;
  longitude?: number;
  name: string;
  phone?: string;
  province?: string;
  province_code?: string;
  zip?: string;
}
