/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBookingBuyer} from './customerBookingBuyer';
import type {CustomerBookingLineItemsItem} from './customerBookingLineItemsItem';

export interface CustomerBooking {
  buyer: CustomerBookingBuyer;
  cancelledAt: Date;
  cancelReason: string;
  lineItems: CustomerBookingLineItemsItem[];
  orderId: number;
}
