/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerBookingLineItemsItemStatus =
  (typeof CustomerBookingLineItemsItemStatus)[keyof typeof CustomerBookingLineItemsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingLineItemsItemStatus = {
  fulfilled: 'fulfilled',
  onhold: 'onhold',
  unfulfilled: 'unfulfilled',
  cancelled: 'cancelled',
  refunded: 'refunded',
} as const;
