/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerPayoutAccountType =
  (typeof CustomerPayoutAccountType)[keyof typeof CustomerPayoutAccountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerPayoutAccountType = {
  MOBILE_PAY: 'MOBILE_PAY',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
} as const;
