/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBookingPeriod} from './customerProductBookingPeriod';
import type {CustomerProductUpsertBodyCompareAtPrice} from './customerProductUpsertBodyCompareAtPrice';
import type {CustomerProductLocations} from './customerProductLocations';
import type {CustomerProductNoticePeriod} from './customerProductNoticePeriod';
import type {CustomerProductUpsertBodyPrice} from './customerProductUpsertBodyPrice';
import type {CustomerProductUpsertBodySelectedOptions} from './customerProductUpsertBodySelectedOptions';

export interface CustomerProductUpsertBody {
  bookingPeriod: CustomerProductBookingPeriod;
  breakTime: number;
  compareAtPrice?: CustomerProductUpsertBodyCompareAtPrice;
  duration: number;
  locations: CustomerProductLocations;
  noticePeriod: CustomerProductNoticePeriod;
  price: CustomerProductUpsertBodyPrice;
  scheduleId: string;
  selectedOptions: CustomerProductUpsertBodySelectedOptions;
  variantId: number;
}
