/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccount} from './customerPayoutAccount';

export interface CustomerPayoutAccountGetResponse {
  payload: CustomerPayoutAccount;
  success: boolean;
}
