/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProduct} from './customerProduct';
import type {CustomerProductListAllOf} from './customerProductListAllOf';

export type CustomerProductList = CustomerProduct & CustomerProductListAllOf;
