/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerLocation} from './customerLocation';
import type {CustomerLocationIsDefaultAllOf} from './customerLocationIsDefaultAllOf';

export type CustomerLocationIsDefault = CustomerLocation &
  CustomerLocationIsDefaultAllOf;
