/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerBlocked {
  _id?: string;
  customerId: number;
  end: string;
  start: string;
  title: string;
  type: string;
}
