/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerBookingsListMode =
  (typeof CustomerBookingsListMode)[keyof typeof CustomerBookingsListMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerBookingsListMode = {
  completed: 'completed',
  upcoming: 'upcoming',
} as const;
