/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductNoticeUnit} from './customerProductNoticeUnit';

export interface CustomerProductNoticePeriod {
  unit: CustomerProductNoticeUnit;
  value: number;
}
