/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBaseOrderAddress} from './customerBaseOrderAddress';
import type {CustomerBaseOrderCustomerSmsMarketingConsent} from './customerBaseOrderCustomerSmsMarketingConsent';

export interface CustomerBaseOrderCustomer {
  accepts_marketing: boolean;
  accepts_marketing_updated_at?: string;
  admin_graphql_api_id: string;
  created_at: string;
  currency: string;
  default_address?: CustomerBaseOrderAddress;
  email?: string;
  email_marketing_consent?: boolean;
  first_name: string;
  id: number;
  last_name: string;
  marketing_opt_in_level?: string;
  multipass_identifier?: string;
  note?: string;
  phone?: string;
  sms_marketing_consent?: CustomerBaseOrderCustomerSmsMarketingConsent;
  state: string;
  tags: string;
  tax_exempt: boolean;
  tax_exemptions?: string[];
  updated_at: string;
  verified_email: boolean;
}
