/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBaseOrderShippingLinesPriceSetPresentmentMoney} from './customerBaseOrderShippingLinesPriceSetPresentmentMoney';
import type {CustomerBaseOrderShippingLinesPriceSetShopMoney} from './customerBaseOrderShippingLinesPriceSetShopMoney';

export type CustomerBaseOrderShippingLinesPriceSet = {
  presentment_money: CustomerBaseOrderShippingLinesPriceSetPresentmentMoney;
  shop_money: CustomerBaseOrderShippingLinesPriceSetShopMoney;
};
