/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBaseOrderMoneyPresentmentMoney} from './customerBaseOrderMoneyPresentmentMoney';
import type {CustomerBaseOrderMoneyShopMoney} from './customerBaseOrderMoneyShopMoney';

export interface CustomerBaseOrderMoney {
  presentment_money: CustomerBaseOrderMoneyPresentmentMoney;
  shop_money: CustomerBaseOrderMoneyShopMoney;
}
