/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerBooking } from './customerBooking';

export interface CustomerBookingGetByGroupIdResponse {
  payload: CustomerBooking;
  success: boolean;
}
