/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {User} from './user';

export interface CustomerLocationRemoveResponse {
  payload: User;
  success: boolean;
}
