/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerPayoutAccount} from './customerPayoutAccount';

export interface CustomerPayoutAccountCreateResponse {
  payload: CustomerPayoutAccount;
  success: boolean;
}
