/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductOptionsAddResponsePayload} from './customerProductOptionsAddResponsePayload';

export interface CustomerProductOptionsAddResponse {
  payload: CustomerProductOptionsAddResponsePayload;
  success: boolean;
}
