/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerBlockedRangeParams = {
  /**
   * start of date
   */
  start: string;
  /**
   * end of date
   */
  end: string;
};
