/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerBaseOrderClient} from './customerBaseOrderClient';
import type {CustomerBaseOrderMoney} from './customerBaseOrderMoney';
import type {CustomerBaseOrderCustomer} from './customerBaseOrderCustomer';
import type {CustomerBaseOrderFulfillment} from './customerBaseOrderFulfillment';
import type {CustomerBaseOrderRefund} from './customerBaseOrderRefund';
import type {CustomerBaseOrderAddress} from './customerBaseOrderAddress';
import type {CustomerBaseOrderShippingLinesPropertyItem} from './customerBaseOrderShippingLinesPropertyItem';

export interface CustomerBaseOrder {
  admin_graphql_api_id: string;
  buyer_accepts_marketing: boolean;
  cancel_reason?: string;
  cancelled_at?: string;
  client_details?: CustomerBaseOrderClient;
  closed_at?: string;
  confirmed: boolean;
  contact_email?: string;
  created_at: string;
  currency: string;
  current_subtotal_price: string;
  current_subtotal_price_set: CustomerBaseOrderMoney;
  /** @nullable */
  current_total_additional_fees_set?: CustomerBaseOrderMoney;
  current_total_discounts: string;
  current_total_discounts_set: CustomerBaseOrderMoney;
  /** @nullable */
  current_total_duties_set?: CustomerBaseOrderMoney;
  current_total_price: string;
  current_total_price_set: CustomerBaseOrderMoney;
  current_total_tax: string;
  current_total_tax_set: CustomerBaseOrderMoney;
  customer: CustomerBaseOrderCustomer;
  fulfillments: CustomerBaseOrderFulfillment[];
  id: number;
  order_number: number;
  refunds: CustomerBaseOrderRefund[];
  /** @nullable */
  shipping_address?: CustomerBaseOrderAddress;
  shipping_lines: CustomerBaseOrderShippingLinesPropertyItem[];
}
