/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type CustomerBaseOrderCustomerSmsMarketingConsent = {
  consent_collected_from?: string;
  consent_updated_at?: string;
  opt_in_level?: string;
  state?: string;
} | null;
