/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomeBaserOrderLineItem} from './customeBaserOrderLineItem';
import type {CustomerLocationBase} from './customerLocationBase';
import type {Shipping} from './shipping';
import type {CustomerBookingAllOfUser} from './customerBookingAllOfUser';

export type CustomerBookingAllOf = {
  end: string;
  groupId: string;
  line_items: CustomeBaserOrderLineItem[];
  location: CustomerLocationBase;
  shipping?: Shipping;
  start: string;
  title: string;
  user: CustomerBookingAllOfUser;
};
