/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerOrderSingleLineItem} from './customerOrderSingleLineItem';

export interface CustomerOrderListResponse {
  payload: CustomerOrderSingleLineItem[];
  success: boolean;
}
