/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type ErrorsErrorsItem = {
  code: string;
  expected?: string;
  message: string;
  path: string[];
  received?: number;
};
