/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { Errors } from './errors';

/**
 * Forbidden
 */
export type ForbiddenResponseResponse = Errors;
