/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { LocationTravelTimeDistance } from './locationTravelTimeDistance';
import type { LocationTravelTimeDuration } from './locationTravelTimeDuration';

export interface LocationTravelTime {
  distance: LocationTravelTimeDistance;
  duration: LocationTravelTimeDuration;
}
