/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { LocationTravelTime } from './locationTravelTime';

export interface LocationGetTravelTimeResponse {
  payload: LocationTravelTime;
  success: boolean;
}
