/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { MetaItem } from './metaItem';

export type Metaspecialties200 = {
  payload: MetaItem[];
  success: boolean;
};
