/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { Errors } from './errors';

/**
 * Not found
 */
export type NotFoundResponseResponse = Errors;
