/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {OpenAIProfileBodyProductsItem} from './openAIProfileBodyProductsItem';
import type {OpenAIProfileBodyUser} from './openAIProfileBodyUser';

export type OpenAIProfileBody = {
  products: OpenAIProfileBodyProductsItem[];
  professions: string[];
  skills: string[];
  user: OpenAIProfileBodyUser;
};
