/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {OpenAIProductTitle200PayloadCollection} from './openAIProductTitle200PayloadCollection';

export type OpenAIProductTitle200Payload = {
  collection?: OpenAIProductTitle200PayloadCollection;
  description: string;
  title: string;
};
