/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {OpenAIProductTitle200Payload} from './openAIProductTitle200Payload';

export type OpenAIProductTitle200 = {
  payload: OpenAIProductTitle200Payload;
  success: boolean;
};
