/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type OpenAIProfile200Payload = {
  aboutMe: string;
  professions: string[];
  shortDescription: string;
  skills: string[];
};
