/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {OpenAIProfile200Payload} from './openAIProfile200Payload';

export type OpenAIProfile200 = {
  payload: OpenAIProfile200Payload;
  success: boolean;
};
