/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type ProductsGetUsersByVariantImagesProfile = {
  height: number;
  url: string;
  width: number;
};
