/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {ProductsGetUsersResponseUsersItem} from './productsGetUsersResponseUsersItem';

export interface ProductsGetUsersResponse {
  productId: number;
  totalUsers: number;
  users: ProductsGetUsersResponseUsersItem[];
}
