/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type ProductsGetUsersByVariantParams = {
  /**
   * product Id
   */
  productId: string;
  /**
   * variant Id
   */
  variantId?: string;
  /**
   * nextCursor
   */
  nextCursor?: string;
  /**
   * limit items (default 5)
   */
  limit?: string;
};
