/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {LocationTravelTime} from './locationTravelTime';
import type {ShippingCalculateResponsePayloadAllOf} from './shippingCalculateResponsePayloadAllOf';

export type ShippingCalculateResponsePayload = LocationTravelTime &
  ShippingCalculateResponsePayloadAllOf;
