/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerLocation } from './customerLocation';

export type ShippingAllOf = {
  _id: string;
  created_at: string;
  location: string;
  origin: CustomerLocation;
  updated_at: string;
};
