/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {ShippingCreateResponsePayload} from './shippingCreateResponsePayload';

export interface ShippingCreateResponse {
  payload: ShippingCreateResponsePayload;
  success: boolean;
}
