/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {ShippingCreateResponsePayloadAllOfCost} from './shippingCreateResponsePayloadAllOfCost';
import type {ShippingCreateResponsePayloadAllOfDestination} from './shippingCreateResponsePayloadAllOfDestination';
import type {CustomerLocationCreateBody} from './customerLocationCreateBody';

export type ShippingCreateResponsePayloadAllOf = {
  _id?: string;
  cost: ShippingCreateResponsePayloadAllOfCost;
  destination?: ShippingCreateResponsePayloadAllOfDestination;
  location?: string;
  origin?: CustomerLocationCreateBody;
};
