/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {ShippingCalculateResponsePayload} from './shippingCalculateResponsePayload';

export interface ShippingCalculateResponse {
  payload: ShippingCalculateResponsePayload;
  success: boolean;
}
