/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {LocationTravelTime} from './locationTravelTime';
import type {ShippingCreateResponsePayloadAllOf} from './shippingCreateResponsePayloadAllOf';

export type ShippingCreateResponsePayload = LocationTravelTime &
  ShippingCreateResponsePayloadAllOf;
