/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {NumberOrString} from './numberOrString';
import type {ShippingBodyDestination} from './shippingBodyDestination';

export interface ShippingBody {
  customerId?: NumberOrString;
  destination: ShippingBodyDestination;
  locationId: string;
}
