/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface UploadResponse {
  id: string;
  purgeHistoryDeleteUri: string;
  restartPostUri: string;
  resumePostUri: string;
  rewindPostUri: string;
  sendEventPostUri: string;
  statusQueryGetUri: string;
  suspendPostUri: string;
  terminatePostUri: string;
}
