/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerLocation } from './customerLocation';
import type { CustomerScheduleSlot } from './customerScheduleSlot';

export interface UserScheduleWithLocations {
  _id: string;
  customerId: number;
  locations: CustomerLocation[];
  name: string;
  slots: CustomerScheduleSlot[];
}
