/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserScheduleWithLocations} from './userScheduleWithLocations';
import type {UserScheduleGetResponsePayloadAllOf} from './userScheduleGetResponsePayloadAllOf';

export type UserScheduleGetResponsePayload = UserScheduleWithLocations &
  UserScheduleGetResponsePayloadAllOf;
