/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersSearchSortOrder =
  (typeof UsersSearchSortOrder)[keyof typeof UsersSearchSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersSearchSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
