/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersListParams = {
  /**
   * nextCursor
   */
  nextCursor?: string;
  /**
   * limit items (default 10)
   */
  limit?: string;
  /**
   * profession like makeup_artist
   */
  profession?: string;
  /**
   * asc or desc
   */
  sortOrder?: string;
};
