/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserScheduleWithLocations} from './userScheduleWithLocations';
import type {UserScheduleGetByProductIdResponsePayloadAllOf} from './userScheduleGetByProductIdResponsePayloadAllOf';

export type UserScheduleGetByProductIdResponsePayload =
  UserScheduleWithLocations & UserScheduleGetByProductIdResponsePayloadAllOf;
