/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserTop } from './userTop';

export type UsersTopResponsePayloadItem = {
  profession: string;
  totalUsers: string;
  users: UserTop[];
};
