/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export interface UserAvailabilityGetBody {
  fromDate: string;
  productIds: string[];
  shippingId?: string;
  toDate: string;
}
