/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserSchedule} from './userSchedule';
import type {UserScheduleGetResponsePayloadAllOf} from './userScheduleGetResponsePayloadAllOf';

export type UserScheduleGetResponsePayload = UserSchedule &
  UserScheduleGetResponsePayloadAllOf;
