/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersFiltersPayloadSpecialtiesItem = {
  count: number;
  speciality: string;
};
