/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UsersProfessionsResponsePayload} from './usersProfessionsResponsePayload';

export interface UsersProfessionsResponse {
  payload: UsersProfessionsResponsePayload;
  success: boolean;
}
