/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductList} from './customerProductList';

export interface UserProductsGetResponse {
  payload: CustomerProductList;
  success: boolean;
}
