/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserAvailabilitySlot} from './userAvailabilitySlot';

export type UserAvailabilitySingleAllOf = {
  slot: UserAvailabilitySlot;
};
