/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UsersSearchBodyLocationLocationType} from './usersSearchBodyLocationLocationType';

export type UsersSearchBodyLocation = {
  city: string;
  locationType: UsersSearchBodyLocationLocationType;
};
