/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserAvailabilitySlotProductsItemPrice} from './userAvailabilitySlotProductsItemPrice';

export type UserAvailabilitySlotProductsItem = {
  breakTime: number;
  duration: number;
  from: string;
  price: UserAvailabilitySlotProductsItemPrice;
  productId: number;
  to: string;
  variantId: number;
};
