/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserImages } from './userImages';
import type { UserSocial } from './userSocial';
import type { UserTheme } from './userTheme';

export interface User {
  aboutMe: string;
  active: boolean;
  customerId: number;
  email: string;
  fullname: string;
  gender: string;
  images: UserImages;
  isBusiness: boolean;
  phone: string;
  professions: string[];
  shortDescription: string;
  social: UserSocial;
  speaks: string[];
  specialties: string[];
  theme: UserTheme;
  username: string;
  yearsExperience: string;
}
