/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserAvailability} from './userAvailability';
import type {UserAvailabilitySingleAllOf} from './userAvailabilitySingleAllOf';

export type UserAvailabilitySingle = UserAvailability &
  UserAvailabilitySingleAllOf;
