/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserUsernameTakenResponsePayload } from './userUsernameTakenResponsePayload';

export interface UserUsernameTakenResponse {
  payload: UserUsernameTakenResponsePayload;
  success: boolean;
}
