/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UserAvailabilitySlotProductsItem = {
  breakTime: number;
  duration: number;
  from: string;
  parentId?: number;
  productId: number;
  to: string;
  variantId: number;
};
