/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBase} from './customerProductBase';
import type {UserScheduleProductAllOf} from './userScheduleProductAllOf';

export type UserScheduleProduct = CustomerProductBase &
  UserScheduleProductAllOf;
