/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersFiltersPayloadLocationsItemLocationType =
  (typeof UsersFiltersPayloadLocationsItemLocationType)[keyof typeof UsersFiltersPayloadLocationsItemLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersFiltersPayloadLocationsItemLocationType = {
  origin: 'origin',
  destination: 'destination',
} as const;
