/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {User} from './user';
import type {UserSchedulesAllOf} from './userSchedulesAllOf';

export type UserSchedules = User & UserSchedulesAllOf;
