/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersFiltersPayloadProductDetailsItem = {
  count: number;
  productHandle: string;
  productId: string;
};
