/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type { UserScheduleProductWithLocations } from './userScheduleProductWithLocations';

export type UserScheduleGetByLocationResponsePayloadAllOf = {
  products: UserScheduleProductWithLocations[];
};
