/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserScheduleWithLocations} from './userScheduleWithLocations';
import type {UserScheduleGetByLocationResponsePayloadAllOf} from './userScheduleGetByLocationResponsePayloadAllOf';

export type UserScheduleGetByLocationResponsePayload =
  UserScheduleWithLocations & UserScheduleGetByLocationResponsePayloadAllOf;
