/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserAvailability} from './userAvailability';
import type {UserAvailabilityMultiAllOf} from './userAvailabilityMultiAllOf';

export type UserAvailabilityMulti = UserAvailability &
  UserAvailabilityMultiAllOf;
