/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UserImages} from './userImages';
import type {UserSocial} from './userSocial';

export interface User {
  aboutMe: string;
  customerId: number;
  email: string;
  fullname: string;
  gender: string;
  images: UserImages;
  phone: string;
  professions: string[];
  shortDescription: string;
  social: UserSocial;
  speaks: string[];
  specialties: string[];
  username: string;
  yearsExperience: string;
}
