/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {CustomerProductBase} from './customerProductBase';

export interface UserProductsGetProductsResponse {
  payload: CustomerProductBase[];
  success: boolean;
}
