/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */

export type UsersSearchBodyLocationLocationType =
  (typeof UsersSearchBodyLocationLocationType)[keyof typeof UsersSearchBodyLocationLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersSearchBodyLocationLocationType = {
  home: 'home',
  commercial: 'commercial',
  destination: 'destination',
  virtual: 'virtual',
} as const;
