/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking Shopify Api
 * OpenAPI spec version: 1.0.0
 */
import type {UsersSpecialtiesResponsePayload} from './usersSpecialtiesResponsePayload';

export interface UsersSpecialtiesResponse {
  payload: UsersSpecialtiesResponsePayload;
  success: boolean;
}
