name: Extract Shopify Preview Link

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comment:
    if: contains(github.event.comment.body, 'Preview deployment')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Preview URL
        id: extract_url
        run: |
          echo "Extracting URL..."
          URL=$(node -e "const body = process.env.COMMENT_BODY; const match = body.match(/Preview deployment.*?(http[s]?:\/\/[^\s]+)/); if (match) console.log(match[1]);" )
          echo "::set-output name=preview_url::$URL"
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Use the Extracted URL
        run: echo "The extracted URL is ${{ steps.extract_url.outputs.preview_url }}"
