name: Test Deployment Preview

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Details
        run: |
          echo "Event Payload: ${{ toJson(github.event) }}"
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "Is PR? : ${{ github.event.issue.pull_request != null }}"
          echo "Contains Expected Text? : ${{ contains(github.event.comment.body, 'Oxygen deployed a preview of your') }}"

      - name: Check Conditions
        if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'Oxygen deployed a preview of your') && github.event.comment.user.login == 'shopify[bot]'
        run: |
          echo "The job conditions are met. Proceeding with actions."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Details
        run: |
          echo "Comment was made by Shopify bot and contains the deployment preview link."

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Extract Preview URL
        run: |
          URL=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=\[Preview deployment\]\().*?(?=\))')
          echo "PREVIEW_URL=$URL" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.PREVIEW_URL }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
